name: Onehit
version: '${project.version}'
main: net.galaxycore.onehit.OneHit
api-version: 1.16
author: Bloeckchengrafik
depend:
  - GalaxyCoreCore
  - LuckPerms

commands:
  ohdb:
    usage: /ohdb [suicide|on|off]
    permission: onehit.debug